# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/default.png', null=True, upload_to='image/%Y/%m'),
        ),
    ]
