# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 10:53
from __future__ import unicode_literals

import apps.article.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('articleid', models.AutoField(primary_key=True, serialize=False, verbose_name='文章Id')),
                ('title', models.CharField(default='', max_length=255, verbose_name='标题')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='副标题')),
                ('context', models.TextField(blank=True, null=True, verbose_name='文章内容')),
                ('createdate', models.DateField(auto_now=True, max_length=100, verbose_name='文章创建日期')),
            ],
            options={
                'verbose_name': '文章库',
                'verbose_name_plural': '文章库',
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='ArticleGroup',
            fields=[
                ('groupid', models.IntegerField(primary_key=True, serialize=False, verbose_name='类型')),
                ('comment', models.CharField(default='', max_length=255, verbose_name='注释')),
                ('parentid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.ArticleGroup')),
            ],
            options={
                'verbose_name': '文章类型',
                'verbose_name_plural': '文章类型',
                'db_table': 'article_group',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('path', models.ImageField(storage=apps.article.storage.ImageStorage(), upload_to='img', verbose_name='路径')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40, verbose_name='名称')),
                ('path', models.CharField(default='', max_length=255, verbose_name='脚本路径')),
                ('type', models.CharField(choices=[('C', 'css脚本'), ('J', 'js脚本')], default='', max_length=2, verbose_name='脚本类型')),
            ],
            options={
                'verbose_name': '脚本',
                'verbose_name_plural': '脚本',
                'db_table': 'script',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleGroup', verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ManyToManyField(blank=True, to='article.Image', verbose_name='需要图片'),
        ),
        migrations.AddField(
            model_name='article',
            name='script',
            field=models.ManyToManyField(blank=True, to='article.Script', verbose_name='需要的脚本'),
        ),
    ]
