# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('articleid', models.IntegerField(primary_key=True, serialize=False, verbose_name='文章Id')),
                ('title', models.CharField(default='', max_length=255, verbose_name='标题')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='副标题')),
                ('context', models.CharField(blank=True, max_length=4000, null=True, verbose_name='文章内容')),
                ('createdate', models.DateField(auto_now=True, max_length=100, verbose_name='文章创建日期')),
            ],
            options={
                'verbose_name': '文章库',
                'db_table': 'article',
                'verbose_name_plural': '文章库',
            },
        ),
        migrations.CreateModel(
            name='ArticleGroup',
            fields=[
                ('groupid', models.IntegerField(primary_key=True, serialize=False, verbose_name='类型Id')),
                ('comment', models.CharField(max_length=255, verbose_name='注释')),
            ],
            options={
                'verbose_name': '文章类型',
                'db_table': 'article_group',
                'verbose_name_plural': '文章类型',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='groupid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleGroup'),
        ),
    ]
