# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='context',
            field=models.TextField(blank=True, null=True, verbose_name='文章内容'),
        ),
    ]
